require('foehnx/plugins')
require('foehnx/settings')
require('foehnx/lsp')
require('foehnx/telescope')
require('foehnx/lualine')
require('foehnx/keybindings')
require('foehnx/bufferline')
require('foehnx/tree')
require('foehnx/mini')
-- require('foehnx/mini_lsp')
require('foehnx/treesitter')
require('foehnx/cleanbuffers')
require('foehnx/toggleterm')
require('foehnx/whichkey')

